version: '3.7'
services:
    github_mock:
      image: gogs/gogs
      container_name: github_mock
      volumes:
          - /tmp/gogs/data:/data
      ports:
          - "10022:22"
          - "10080:3000"
      networks:
        dev_ops:
          ipv4_address: 172.16.238.2
      extra_hosts:
          - "github_mock:172.16.238.2"
          - "localstack:172.16.238.3"
          - "jenkins_master:172.16.238.4"                    
         
    localstack:
      container_name: localstack_main
      image: localstack/localstack:latest
      ports:
        - "4566:4566"
        - "4571:4571"
      networks:
        dev_ops:
          ipv4_address: 172.16.238.3   
      environment:
        - SERVICES=${SERVICES-acm,apigateway
            ,cloudformation,cloudwatch,dynamodb
            ,dynamodbstreams,ec2,es,events
            ,firehose,iam,kinesis,kms,lambda,rds
            ,route53,s3,s3api,secretsmanager,ses,sns
            ,sqs,ssm,stepfunctions,sts}
        - DEBUG=${DEBUG-}
        - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
        - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
        - DOCKER_HOST=unix:///var/run/docker.sock
        - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
        - HOST_TMP_FOLDER=${TMPDIR}
        - LOCALSTACK_HOSTNAME=localstack
        - LAMBDA_REMOTE_DOCKER=false
        - LAMBDA_REMOVE_CONTAINERS=false
        - LAMBDA_DOCKER_NETWORK=jenkins-deploy-lambda-terraform_dev_ops
      volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
      extra_hosts:
          - "github_mock:172.16.238.2"
          - "localstack:172.16.238.3"
          - "jenkins_master:172.16.238.4"                  

    jenkins_master:
      image: jenkins/jenkins:master
      container_name: jenkins_master                
      depends_on:
          - github_mock
          - localstack
      volumes:
          - /tmp/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          - ${AWS_CRED}:/var/jenkins_home/.aws
      links:
          - localstack
          - github_mock
      networks:
        dev_ops:
          ipv4_address: 172.16.238.4
      ports:
          - "8085:8080"
          - "50000:50000"
      extra_hosts:
          - "github_mock:172.16.238.2"
          - "localstack:172.16.238.3"
          - "jenkins_master:172.16.238.4"          

networks:
  dev_ops:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
          gateway: 172.16.238.1        
        
